import { Annotation } from '@langchain/langgraph';
import type { ProfileInformation } from '../types.js';

const arrayReducer = <T>() => (
    state: T[],
    update: {
        append?: T[],
        remove?: T[],
    },
) => {
    const newState = new Set(state);
    const { append = [], remove = [] } = update;
    append.forEach((item) => newState.add(item));
    remove.forEach((item) => newState.delete(item));
    return Array.from(newState);
};
export const StateAnnotation = Annotation.Root({
    /**
     * Profile urls from input. Removed once scraped
     */
    profilesToEvaluate: Annotation<string[], {
        append?: string[],
        remove?: string[],
    }>({
        reducer: arrayReducer<string>(),
        default: () => [],
    }),
    /**
     * Scraped profiles, both from search and input
     */
    scrapedProfiles: Annotation<Record<string, ProfileInformation>, Record<string, ProfileInformation>>({
        reducer: (state, update) => {
            const newState = { ...state };
            Object.entries(update).forEach(([key, value]) => {
                if (value === undefined) {
                    delete newState[key];
                } else {
                    newState[key] = value;
                }
            });
            return newState;
        },
        default: () => ({}),
    }),
    /**
     * Array of profile names whose information will be passed to the LLM for evaluation.
     */
    profilesToLlm: Annotation<string[], {
        append?: string[],
        remove?: string[],
    }>({
        reducer: arrayReducer<string>(),
        default: () => [],
    }),
    influencerDescription: Annotation<string>(),
    /**
     * Search terms that haven't been scraped yet, generated by LLM.
     */
    searchTermsToScrape: Annotation<string[], {
        append?: string[],
        remove?: string[],
    }>({
        reducer: arrayReducer<string>(),
        default: () => [],
    }),
    /**
     * Scraped search terms go here for deduping
     */
    oldSearchTermsToScrape: Annotation<string[], {
        append?: string[],
        remove?: string[],
    }>({
        reducer: arrayReducer<string>(),
        default: () => [],
    }),
    mock: Annotation<boolean>(),
    generatedKeywords: Annotation<number>(),
    profilesPerKeyword: Annotation<number>(),
});

export type State = typeof StateAnnotation.State;
